### ISSUE TITLE
Apo Issue tracker

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#127]
This is the to-do list for @Apogate who is me.

**Comment by Apogate** [comment]
Post linking in reply mode link to a nonexistent page instead of the post link anchor.

Review autolinking.

**Comment by RePod** [comment]
Most of it is hardcoded.

**Comment by Apogate** [comment]
~~`BR_CHECK` and `MAX_LINES` are totally ignored~~ Solved in #153 upon merge

**Comment by Apogate** [comment]
Modifiying any post row in sql changes the root to the time it was edited, per the update timestamp (or whatever) sql flag. This causes stickies to become unstuck if they are autosaged, locked or unlocked after being stuck.

**Comment by RePod** [comment]
Sure page generation wasn't the problem?

**Comment by Apogate** [comment]
>Sure page generation wasn't the problem?

Yes. I noticed this issue myself, but didn't bother to fix it/remind myself to fix it. It was due to the 
    `ON UPDATE CURRENT TIMESTAMP` 
or whatever flag in SQL causing the root to be modified if the `locked` `permasaged` or `sticky` values were modified

**Comment by Apogate** [comment]
`S_OMITT_NUM` is ignored for stickies

**Comment by Apogate** [comment]
Autolinking system definitely needs to be revisited, perhaps rewritten.

**Comment by RePod** [comment]
Autolinking could be done as a TextProcessor with valid regex, may take a few though.

**Comment by Apogate** [comment]
For staff.php:
- [ ] Ability for users to change their own passwords
- [x] Ability for front-end user deletion
- [ ] Allow changing permissions
- [ ] Log all staff modifications possibly

**Comment by Apogate** [comment]
**reports.php**
~~\- [x] Disable reporting for post if user made the post~~ 9222983bb748b7877ceb3cf3c3f7c14ed8d52c26

**Comment by RePod** [comment]
Why can't users report themselves?

**Comment by Apogate** [comment]
Why do morons need to be allowed to make a post, report it, rinse and repeat?

If they're reporting a post, their intent is to get the post deleted. They can just delete the post on their own in that case.

**Comment by Apogate** [comment]
unless that was a joke. in that case. i'm going to delete my autism reply when i get home

**Comment by Apogate** [comment]
Rewrite page, report and delete form at bottom of page to make it less cluttered for mobile users.

**Comment by Apogate** [comment]
saved comment from news.php:

Congrats, you triggered me at the expense of security.

>Adding the class name to the function, or anything relevant to it, is dumb.

----

`newsUpdate()`
----
Security concern of allowing raw PHP code execution, as well as possible XSS attacks.
Obviously an intruder would need to get this far, but if the intruder is able to compromise an account with access to this they could quickly escalate.

~~Would be better if the files store `<` and `>` as `&gt;` and `&lt;` and if being loaded into a textbox, convert back naturally (until stored again).~~ A proper and pre-existing HTML sanitizer would be better, used optionally if available.

`newsGetFile()`
----
It has permission to read any file it wants to instead of pre-defined ones. It'd be best to modify it not to accept a file path, but a pre-determined file indicator similar to `newsUpdate()` which then uses the *BOARDLIST* from the config. Regardless, it has too much power beyond its scope.

In theory (and intentional usage), `echo News::newsGetFile('/var/www/nightmare/config.php');` dumps all of the file given. And since it's plain text, nothing gets obscured.

**Also news.php is missing the closing ?>**

**Comment by Apogate** [comment]
~~\- `<br />` tags aren't being converted properly for non-staff.~~
~~\- thread bumping is broken. entirely.~~

All fixed in #173

**Comment by Apogate** [comment]
Reporters can report one post multiple times

**Comment by RePod** [comment]
Nothing like a super report, is it stored multiple times?

**Comment by Apogate** [comment]
> is it stored multiple times?

yes. which is the problem here

**Comment by Apogate** [comment]
Can't delete users. whoops

**Comment by RePod** [comment]
While it may or may not be a result of SaguaroQL, I think all uses of it should be looked at and revised/optimized to take advantage of the new class.

**Comment by RePod** [comment]
Also instead of closing other issues and lumping into this one to track them [just use the search options](https://github.com/spootTheLousy/saguaro/issues?q=assignee%3AApogate+is%3Aopen).

This makes it harder to actually track the status of actual issues because their original sources get closed.
