### ISSUE TITLE
Stray/unused file cleanup checklist

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#147]
<font color='red'>Scheduled for deletion</font>:
- [x] ~~**/general/head.php**~~ - Replaced by **/page/head.php**
- [ ] Either **/general/text_process/autolink.php** (Class, 2 functions) or its bastard cousin **/thread/autolink.php** (Non class, 5 functions). Neither work properly yet.

<hr>

<font color='gray'>Unused</font>:
- [x] **/index/index.php** ?? Or is it??
- [ ] **/user/user.php** property of repod

<hr>

Unsure:
- [ ] **/general/fortune.php** Work in progress?
- [x] **/general/resredir.php** Unreferenced?

<hr>

Relocate:
- [x] **_core/postform.php** Probably move it to thread class.

**Comment by RePod** [comment]
**/index/index.php** is used by the new Log generation.
**_core/postform.php** is used everywhere. If anything, general is the only place it can go.
**/general/resredir.php** is used by imgboard.php.
**/user/user.php** is forever under construction.
