### ISSUE TITLE
ADMIN PANEL GIGA-TODO LIST

### ISSUE THREAD

**Issue by Apogate** [spootTheLousy/saguaro#69]
Automated board generation can be handled in _admin.php_ (**WHICH _WILL_ REMAIN CLASSLESS**)

I'll add documentation to the wiki for permissions, but for now the setup is:

| Access level (#) | Permission |
| --- | --- |
| **Janitor_this_board** (**1**) | 1. Bypass report flood, Delete posts via browser view |
| **Janitor** (**5**) | Allowed deletion across multiple boards, above permissions |
| **Moderator** (**10**) | Delete posts by IP, access to admin panel, thread tools (Sticky, lock, permasage), Imageless posting/flood bypass |
| **Manager** (**20**) | Global board rebuild, user management for those lower on the permission tree, above permissions |
| **Admin** (**50**) | Board creation, user management, above permissions |

<hr>
- [x] Move admin panel to _admin.php_ 
  - This will allow for a more robust admin panel consolidating all the panels into one location instead of a separate panel for each board 
- [ ] User management for Manager+
- [x] Report queue by board
- [ ] Convert $badstring, $badfile into a sql based blacklist, grant permission to modify the blacklist to Moderator+? or Manager+
  - This will be reviewed
  - Blacklist check will be carried out via a single SQL query in _regist.php_ 
- [ ] Moderator+ staff only viewable ban log for client-side ban managing
  ## \* Won't have to tinker in PHPMyAdmin

Bugs to fix:
- [x] Staff can't delete outside the panel *Somewhat fixed in #78 *
- [ ] Deleting a single image from a thread deletes all images in a thread
- [x] Staff can't post images from the admin form: #78 
- [ ] Clean up functions in **admin.php**

**Comment by Apogate** [comment]
* [ ] Convert $badstring, $badfile into a sql based blacklist, grant permission to modify the blacklist to Moderator+? or Manager+
    *This will be reviewed
* [ ] Moderator+ staff only viewable ban log for client-side ban managing
    * Won't have to tinker in PHPMyAdmin

**Comment by Apogate** [comment]
MAKIN PROGRESS

**Comment by RePod** [comment]
You moved out `rebuild()` on its own without moving out the rest of the commands (and back-porting it to maintain legacy support to non-admin commands that may need it in the interim).

See:
- #64 
- #77 

Rebuild should get it's own folder in __core_, and set up to work via proxy (similar to #77) for now.

**Comment by RePod** [comment]
Currently the _reports_ and _loginattempts_ table names are hard-coded to be shared across boards.

While this has advantages, it also has disadvantages.

I've been working on an uninstall/removal function for _test.php_ and I don't want to be deleting these two tables blindly.

**Deleting blindly:**
![](https://i.imgur.com/EfeqyEQ.png)

**Not deleting blindly:**
![](https://i.imgur.com/RP3HEfw.png)

It defeats the purpose of uninstalling a majority but not all of what it created (aside from files, which users should probably delete themselves).

I propose switching the _reports_ and _loginattempts_ tables to be board-specific.

Currently only _admin.php_ uses _reports_.

Users interested in sharing tables can override them in the config by removing the inherited prefix.

**Comment by RePod** [comment]
9e4608aa9409f436b935ec3ad91a204ba021ba72 fixed #78 / "Staff can't post images from the admin form" is fixed. Checked off.

"Clean up functions in admin.php" would involve breaking it up and moving it into **_core/** so it can also be used in multi-board installs (which should also go on the to-do list).

**Comment by Yushe** [comment]
Reports just stay on the reports page there is no way to get rid of them. (I think)
Basically you can't dismiss a report as far as I know.

**Comment by RePod** [comment]
I will get to work on it, or at least bug @Apogate.

This version is still in development so there are a few bugs, thanks for reporting this.

**Comment by Apogate** [comment]
There's no framework right now for deleting reports, I pushed an incomplete feature so people could at least see reports and delete posts which might have bad things.

My next pr will be user management and finalize/optimize report system.

Hang in there

**Comment by Yushe** [comment]
If you quote/reply to a post ">>x" using the admin file to post the post won't be linked it will just be normal text.

**Comment by Yushe** [comment]
Not sure why but the users IP and Comment are not shown on the admin panel or the sql db even if there is a comment. (The comment is shown on posts but not on the admin panel or the sql db)

**Comment by Yushe** [comment]
Okay this is a sort of big issue.

Stickys don't work, sometimes when someone bumps a thread or creates a thread the thread will bump over the sticky. **De-Autosageing a thread fixes this** _I think_.

**Comment by Apogate** [comment]
This is an issue with the way the SQL table is set up, every time a post is updated, the timestamp in 'root' is set to the current time. It'll get fixed eventually

**Comment by RePod** [comment]
Could also be a problem with Index generation, I didn't test stickies that much.

**Comment by Apogate** [comment]
eh

**Comment by RePod** [comment]
> Automated board generation can be handled in admin.php (WHICH WILL REMAIN CLASSLESS)

How the times have changed.
